<?php
/**
 * Created by PhpStorm.
 * User: Nano
 * Date: 19/6/2017
 * Time: 3:41 PM
 */

namespace componentes;

use yii\base\Widget;
use yii\helpers\Html;
use Yii;
use backend\models\Faq;
use backend\models\search\FaqSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;

class FaqWidget extends Widget
{
    public $models;
    public $pages;
    public $pageSize;
    public $settings = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(!isset($this->settings['pageSize'])){
            $this->settings['pageSize'] = 2;
        }

        if($this->settings['featuredOnly'] == true){
            $query = Faq::find()->where(['faqIsFeatured'=>1]);
        }else{
            $query = Faq::find();
        }
        $query->orderBy(['faqWeight'=>SORT_ASC]);
        $countQuery = clone $query;
        $this->pages = new Pagination(['defaultPageSize'=>$this->settings['pageSize'],'totalCount'=>$countQuery->count()]);
        $this->models = $query->offset($this->pages->offset)->limit($this->pages->limit)->all();
    }

    public function run()
    {
        return $this->render('faq',[
            'models' => $this->models,
            'pages' => $this->pages,
            'settings' => $this->settings,
        ]);
    }


}